# Windows legs
parameters:
  # Required: value to specify if the job is coming from an official build to run extra steps and sign binaries
  #   Default: false
  isOfficialBuild: false
  # Required: value to specify if the full test matrix should be tested
  #   Default: false
  fullMatrix: false
  # Optional: value to scope the tests.
  #   Default: empty
  testScope: ''

jobs:

- template: base.yml
  parameters:
    isOfficialBuild: ${{ parameters.isOfficialBuild }}
    testScope: ${{ parameters.testScope }}
    targetOS: Windows_NT
    jobs:

    # Legs with testing
    - job: WindowsTest
      displayName: Windows
      strategy:
        matrix:
          # PR CI Matrix
          ${{ if eq(parameters.fullMatrix, 'false') }}:
            x64_Debug:
              _BuildConfig: Debug
              _architecture: x64
              _framework: netcoreapp

          # Full test matrix
          ${{ if eq(parameters.fullMatrix, 'true') }}:
            x64_Release:
              _BuildConfig: Release
              _architecture: x64
              _framework: netcoreapp
              _publishTests: true

            NETFX_x64_Release:
              _BuildConfig: Release
              _architecture: x64
              _framework: netfx
              _skipPublishPackages: true # In NETFX leg we don't produce packages

      pool:
        vmImage: 'windows-latest'

      buildExtraArguments: /p:RuntimeOS=win10
